### ISSUE TITLE
process

### ISSUE THREAD

**Issue by obissick** [Percona-Lab/mongodb_consistent_backup#242]
Why is mongodb_consistent_backup user running polkitd process on a server i didnt install it on? This server is not even a MongoDB server.

**Comment by dbmurphy** [comment]
This is not run by this tool, this is a python library something else like s3cmd via pythons boto library would maybe cause this, but it’s normally systemd that would trigger it.

**Comment by timvaillancourt** [comment]
@dbmurphy is correct, this tool only spawn Python and/or "mongodump" binaries. You can confirm this also by reading the python source code.

If polkitd is running as the same user as the 'mongodb_consistent_backup' user this could be due to duplicated numeric user ids or it was started before a change to /etc/passwd.

**Comment by timvaillancourt** [comment]
Closing due to no reply.
